spring.application.name=spring-boot-library

spring.datasource.url=jdbc:postgresql://localhost:5432/reactlibrarydatabase
spring.datasource.username=app_developer
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=none

server.servlet.context-path=/api

server.max-http-request-header-size=80MB
spring.jpa.show-sql=true

# okta.oauth2.client-id env variable
# okta.oauth2.issuer env variable
okta.oauth2.audience=https://localhost:8443

// stripe.key.secret - env variable

####################
#   HTTPS config
####################

server.port=8443

server.ssl.enabled=true

server.ssl.key-alias=springbootkey

server.ssl.key-store=classpath:springboot-keystore.p12

server.ssl.key-store-password=secret

server.ssl.key-store-type=PKCS12